env:
    DB_HOST: ENC[AES256_GCM,data:w+JWVlIpNUJWh9+8+n8WNOD3IqokQmpYNgS8FKfWdw==,iv:rXlBOcSLa14vlgFzSUuBVR40if+wNZcKZaR3tO22DHU=,tag:7a8Mhs3tC93wLMpguceAwA==,type:str]
    DB_NAME: ENC[AES256_GCM,data:fNmCvzq3i1ZBevY=,iv:2XSi2UkbxFwVQVeNWSv6kuz3FWWOdvkKOzp8mt9pqMU=,tag:Lh+9hU1aT75Trg+vfecPzA==,type:str]
    DB_USER: ENC[AES256_GCM,data:5NJlgg==,iv:A+xhQCL5moLGqHz9tkhBWkkU2Unx1OIEhC01dHQ5bgI=,tag:BU2cRrlIGieBv7oeBszIBw==,type:str]
    DB_PASS: ENC[AES256_GCM,data:R2UvJ885/w2knII=,iv:lvdRBNS4HGyhrcxXZ20afDNWaWHn9DxT2XiR72gJrFY=,tag:MNaPA5cXaQUmw/wVklohJQ==,type:str]
mysql:
    mysqlRootPassword: ENC[AES256_GCM,data:1ub7/iVfdYxvi4k=,iv:aIQaCo/49gATE/sizS3uNeVhaa+f2UTxaeyDBLwkBQ0=,tag:Vr14Za+1A5Y+N5GZmeLX1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    lastmodified: '2019-02-14T13:14:55Z'
    mac: ENC[AES256_GCM,data:e+nVCjE63PgxtyqoLV6dVwp0PaxJ9z5AKfo3ak715M5CxnfbESlLq50dm5hsmKO7FcqJ7E6tWtbLuIkLy1wo+K70cJGuse13/E2Ul/73NEtnAzG8g4Yp/TpP140vN5+k24yFHAoQZccFL1pXdhf8l+H4ewXH7hrQpeZOl5cM6IE=,iv:0x2nvTSEqv6Yr55MqWCsVn9LP0zJ8RxBILI+aJUIhiM=,tag:59l08IweSRkF3h5xlBGIdg==,type:str]
    pgp:
    -   created_at: '2019-02-13T18:42:55Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA2c8WqZTjOTFAQv8DuOCJguQVFpbXqpLt6fpJ1v/VKiX0x30fJw/W54unY48
            amDQC4MA90j1R/UjOYAUfeLxRs6Drj/Vy/L8Guxh0vqAhORfhJdJuuo3lsp6wLtF
            S+JwbN9LlZq9XVWkXtoQ3YmaKglykaE12TKMM5qw+IEjW+fBTpZQi2wl6Akhd8ea
            VwCFwLNY14/kVQ+H4hrMNQ1P9jKru6ubvZOB9e/n5HxZwAtluYsm83pgvzYuU97t
            K/OYLputlkNKIy9/9/mTvpEuXqC4mC01oh+383l5CQi/vdWYs1iX/k+awsu+B9dF
            4bmN/mVoNQ1lj7Q8X70tZbkXP8aHuUCAnOVDCjvo+OrK+Z+KiQQ4NuNtC2sajDJG
            TjlG/lCI+srdCPXEZ50YsrsXYPdwCXxG6IA4pHaTBtsX8hkmprtOxsqTHwHJRs+n
            m1mbki4FfZC8bbZmntAnPaR8Qdll9FLa4+PzFMMQCcJEFk6U0mbzO1B+559JM2LU
            B318hSQ/9Ha3nD5dY6UH0l4BtE/BkIjyoS6QQ71yFEe8vTW5zALq+X6rARTUJ0lz
            th/ULA/R7WWMJehSteizNE2GuUfxhETu+Gil20wE2clq6+1e01yzM7KUexnwZ+et
            8Otex7pxM0/FtivGmjSL
            =FnI3
            -----END PGP MESSAGE-----
        fp: C850D2D8D0CCAFC15B6DD4894D26191663D05BEE
    unencrypted_suffix: _unencrypted
    version: 3.0.3
