replicaCount: 1

image:
  repository: stumblefunk-accreditation
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

mysql:
  enabled: true
  persistence:
    enabled: true
    storageClass: manual
    subPath: stumblefunk-accreditation-mysql
  mysqlDatabase: stumblefunk
  configurationFiles:
    mysql.cnf: |-
      [mysqld]
      skip-host-cache
      skip-name-resolve
  initializationFiles:
    stumblefunk-groups.sql: |- 
      USE stumblefunk; CREATE TABLE groups (`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY, group_name varchar(255), kids int(5), adults int(5), vehicles int(5), last_action datetime, guid varchar(25))ENGINE=innodb;
    stumblefunk-tickets.sql: |- 
      USE stumblefunk; CREATE TABLE tickets (`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY, guid varchar(25), ticket_type varchar(255), first_name varchar(255), last_name varchar(255), email varchar(255), mobile varchar(255), vehicle_reg varchar(255), vehicle_pass varchar(255), last_action datetime) ENGINE=innodb;
    stumblefunk-sessions.sql: |- 
      USE stumblefunk; CREATE TABLE sessions (`id` varchar(32) NOT NULL, access int(10) unsigned, data text, PRIMARY KEY (id));

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  paths:
    - /
  hosts:
    - stumblefunk-accreditation.k8s.squiggle.org
  tls: []
