apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stumblefunk-accreditation.fullname" . }}-db
  labels:
    app: {{ include "stumblefunk-accreditation.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  DB_NAME: {{ .Values.env.DB_NAME | b64enc | quote }}
  DB_HOST: {{ .Values.env.DB_HOST | b64enc | quote }}
  DB_USER: {{ .Values.env.DB_USER | b64enc | quote }}
  DB_PASS: {{ .Values.env.DB_PASS | b64enc | quote }}
