name: Build React App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Change working directory
      run: cd frontend

    - name: Use Node.js LTS
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'

    - name: Install dependencies
      run: pwd && npm install

    - name: Build React app
      run: npm run build
