name: Build & Deploy

env:
  terraform_version: '1.6.2'
  terragrunt_version: '0.54.22'

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get nodejs version
      uses: actions/setup-node@v4
      with:
        node-version-file: 'frontend/.nvmrc'

    - name: Install dependencies
      working-directory: frontend
      run: npm ci

    - name: Build React app
      working-directory: frontend
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: accreditation
        path: frontend/build
        overwrite: true

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment: dev
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::603042156394:role/_github_actions
        aws-region: eu-west-1

    - name: Terragrunt
      uses: gruntwork-io/terragrunt-action@v2
      with:
        tf_version: ${{ env.terraform_version }}
        tg_version: ${{ env.terragrunt_version }}
        tg_dir: environments/dev
        tg_command: 'apply'

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: accreditation
        path: accreditation
  
    - name: Copy to S3
      run: aws s3 sync accreditation s3://stumblefunk-www-dev/accreditation

    - name: Load env config
      run: aws s3 cp s3://stumblefunk-www-dev/accreditation/config.js.env s3://stumblefunk-www-dev/accreditation/config.js


  deploy-prod:
    runs-on: ubuntu-latest
    needs: [build, deploy-dev]
    environment: prod
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::603042156394:role/_github_actions
        aws-region: eu-west-1

    - name: Terragrunt
      uses: gruntwork-io/terragrunt-action@v2
      with:
        tf_version: ${{ env.terraform_version }}
        tg_version: ${{ env.terragrunt_version }}
        tg_dir: environments/dev
        tg_command: 'apply'

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: accreditation
        path: accreditation
  
    - name: Copy to S3
      run: aws s3 sync accreditation s3://stumblefunk-www-dev/accreditation

    - name: Load env config
      run: aws s3 cp s3://stumblefunk-www-dev/accreditation/config.js.env s3://stumblefunk-www-dev/accreditation/config.js